# coding: utf-8

"""
    Gaming Platform API

    REST API for a gaming platform

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_games_get(self) -> None:
        """Test case for games_get

        Get all games
        """
        pass

    def test_games_id_delete(self) -> None:
        """Test case for games_id_delete

        Delete a game
        """
        pass

    def test_games_id_get(self) -> None:
        """Test case for games_id_get

        Get a game by ID
        """
        pass

    def test_games_id_put(self) -> None:
        """Test case for games_id_put

        Update a game
        """
        pass

    def test_games_post(self) -> None:
        """Test case for games_post

        Add a new game
        """
        pass

    def test_players_get(self) -> None:
        """Test case for players_get

        Get all players
        """
        pass

    def test_players_id_delete(self) -> None:
        """Test case for players_id_delete

        Delete a player
        """
        pass

    def test_players_id_get(self) -> None:
        """Test case for players_id_get

        Get player info
        """
        pass

    def test_players_id_put(self) -> None:
        """Test case for players_id_put

        Update player info
        """
        pass

    def test_players_post(self) -> None:
        """Test case for players_post

        Register a new player
        """
        pass


if __name__ == '__main__':
    unittest.main()
